### ISSUE TITLE
missing information in schedule

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#10]
Episodes 14 and 15 are not showing up in the schedule or the episode tab. However, the files for the episode appear to be properly formatted. 

![screen shot 2018-03-23 at 12 31 16 pm](https://user-images.githubusercontent.com/7544197/37838239-28514cd6-2e96-11e8-8895-b344fa49efc2.png)
![screen shot 2018-03-23 at 12 30 37 pm](https://user-images.githubusercontent.com/7544197/37838237-281f993e-2e96-11e8-9f3d-c73133dcfa18.png)

**Comment by raynamharris** [comment]
I figured it out @fmichonneau ! It's because some of the yaml header was translated. I'll correct this now.

**Comment by fmichonneau** [comment]
thanks for figuring it out because I couldn't spot the issue!
