### ISSUE TITLE
reference not rendering

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#110]
The reference page isn't rendering appropriately. 

![screen shot 2019-01-19 at 1 09 59 pm](https://user-images.githubusercontent.com/7544197/51431231-8db19200-1beb-11e9-9cdf-e747b79022cc.png)

**Comment by fmichonneau** [comment]
fixed by https://github.com/swcarpentry/r-novice-gapminder-es/commit/58051651439f6bcf4ebc6ba0534c5c961ce74709
