### ISSUE TITLE
Sugerencias en traducción 04-data-structures-part1.Rmd

### ISSUE THREAD

**Issue by Yalbibalderas** [swcarpentry/r-novice-gapminder-es#123]
Hola, les envío las siguientes sugerencias para mejorar esta lección 

Línea 53 cambiar function por función (en español)

Línea 63 cambiar a español: # guardar el archivo para usarlo en otra lección más adelante

La línea 210 se entendería mejor si dice algo así: Como puedes notar, es sorprendente ver qué pasa cuando R fuerza la conversión de un tipo de datos en otro tipo…. 

La línea 369 se entendería mejor si dice algo así: Ahora veamos algo interesante acerca de nuestro **data.frame**; ¿Qué pasa si corremos la siguiente línea?

Línea 406 cambiar sutílmente por sutilmente (sin acento)

Línea 446 cambiar sólo por solo (sin acento)

**Comment by Helysalgado** [comment]
Línea 53 cambiar function por función (en español)

ok corregido.

Línea 63 cambiar a español: # guardar el archivo para usarlo en otra lección más adelante

ok   quedo como  "guardar el archivo para usarlo en futuras lecciones"

La línea 210 se entendería mejor si dice algo así: Como puedes notar,  es sorprendente ver qué pasa cuando R fuerza la conversión de un tipo  de datos en otro tipo….

ok "Como puedes notar, es sorprendete ver qué pasa cuando R forza la conversión de un tipo de datos a otro."

La línea 369 se entendería mejor si dice algo así: Ahora veamos algo interesante acerca de nuestro data.frame; ¿Qué pasa si corremos la siguiente línea?

ok aceptada la suferencia.

Línea 406 cambiar sutílmente por sutilmente (sin acento)

ok

Línea 446 cambiar sólo por solo (sin acento)
ok
