### ISSUE TITLE
contribución de lección - Manipulación de data frames con dplyr

### ISSUE THREAD

**Issue by Talishask** [swcarpentry/r-novice-gapminder-es#131]
Soy del The Carpentries Core Team y envío este contribución para otro miembro de la comunidad. 

---

Por favor vea la contribución adjunta
[Contribuciónlección.pdf](https://github.com/swcarpentry/r-novice-gapminder-es/files/9842900/Contribucionleccion.pdf)

**Comment by nselem** [comment]
Hello @Talishask 

I thank Claudia Guerrero for the effort in this contirbution. 

I have noticed that this are extra exercises to the lesson in the section filter(), and group_by().  Despite these are good examples of how to use filter and gorup_by these extra examples would increase the episode size making difficult to terminate on time and would focus too much on this two sections. For that reason I do not include them as part of the lesson. Instead, in the filter() section there is a need for an explanation of the first exercise, we encourage the contributor to develop this part.   

Thank your for your suggestion.
