### ISSUE TITLE
data examples - language issue

### ISSUE THREAD

**Issue by catalicu** [swcarpentry/r-novice-gapminder-es#133]
In 'Extructuras de datos', the example dataset is initially created within r with column names and character strings in Spanish:
gatos <- data.frame(color = c("mixto", "negro", "atigrado"),
                      peso = c(2.1, 5.0, 3.2),
                      le_gusta_cuerda = c(1, 0, 1))  

However, later on, it is imported form the file feline-data.csv, which has the column names and character strings in English:
gatos <- read.csv(file = "data/feline-data.csv")
gatos
    coat weight likes_string
1 calico    2.1            1
2  black    5.0            0
3  tabby    3.2            1

This issue impacts the following commands. For example, invoking the column 'peso' gives a NULL:
gatos$peso
NULL
because the English version of the dataset is loaded. 
Fixing the language in the text file or keeping the Spanish version loaded should fix this issue.

**Comment by nselem** [comment]
Thank you for letting us know. This issue seem to arise when you load the data from the file feline-data,csv 
I have looked and there are several files in the files directory, such as gatos-data.csv (https://github.com/swcarpentry/r-novice-gapminder-es/tree/main/_episodes_rmd/data) I don't know if it is any reason why the lesson was not updated before to this file [@vjimenez9](https://github.com/vjimenez9)? It there is no reason, then I can update everything to Spanish.

**Comment by catalicu** [comment]
Hi Nelly

No problem! I agree, it is probably an issue of moving from the English encoded data to the Spanish encoded data. I really appreciate the lessons in Spanish! I think it increases the reach of the Carpentries lessons enormously. 



Catalina Cuellar-Gempeler, PhD
Pronouns: she/ella
Assistant Professor
Department of Biological Sciences
Humboldt State University
***@***.***

To schedule an appointment: https://catalina-cuellar-gempeler.youcanbook.me

**Comment by nselem** [comment]
Hello, 
This issue is similar to [issue#78]. Now the colors are in Spanish, "feline" has been updated to "gatos" and even the factor tortoiseshell has been updated to "carey". Thanks for the observation.
