### ISSUE TITLE
Repo's maintainers information

### ISSUE THREAD

**Issue by vhmcck** [swcarpentry/r-novice-gapminder-es#151]
### What is the problem?

Hi,

I am reaching out on behalf of the SWC LPGC Committee to report a mismatch between the SWC website and your README file. Would it be possible to please update the maintainers' names on the README file for this repository? We understand the information on the SWC website is up-to-date.

Thanks a lot,
Valentina

### Location of problem (optional)

README file

**Comment by nselem** [comment]
Dear Valentina
Thank you for your contribution. The readme file has been updated with SWC website information.

**Comment by vhmcck** [comment]
Thank you so much, @nselem!
Take care,
Valentina
