### ISSUE TITLE
revisar el episodio 4: "Estructuras de datos"

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#17]
[04-data-structures-part1.Rmd](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/_episodes_rmd/04-data-structures-part1.Rmd)

**Español**
1. Antes de comenzar, consulte el [**Lineamientos de traducción**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
1. Para indicar que estás trabajando en esto, deja un comentario.
- [x] confirmar que términos técnicos no son traducido y son marcado con negrita
- [x] revise la traducción y realice mejoras (por ejemplo, corregir errores tipográficos, mejorar la legibilidad)
- [x] arreglar enlaces rotos
- [x] confirmar que el episodio refleja el [episodio en inglés](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (por ejemplo, sin grandes inserciones o eliminaciones)

**English**
1. Before beginning, consult the [**conventions for translation**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
1. To signal that you are working on this, leave a comment.
- confirm that technical terms are not translated and are marked with bold
- review the translation and make improvements (for example, correct typographical errors, improve readability)
- fix broken links
- confirm that the episode mirrors the [English episode](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (e.g. no large insertions or deletions)

**Comment by Helysalgado** [comment]
revisado

**Comment by Helysalgado** [comment]
Revisados los 4 puntos. Editado directamente, los cambios fueron mínimos.
