### ISSUE TITLE
Revisar episdio 6: Haciendo subconjuntos de datos

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#19]
Rmd archivo: [06-data-subsetting.Rmd](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/_episodes_rmd/06-data-subsetting.Rmd)

**Español**
1. Antes de comenzar, consulte el [**Lineamientos de traducción**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
1. Para indicar que estás trabajando en esto, deja un comentario.
- [x] confirmar que términos técnicos no son traducido y son marcado con negrita
- [x] revise la traducción y realice mejoras (por ejemplo, corregir errores tipográficos, mejorar la legibilidad)
- [x] arreglar enlaces rotos
- [x] confirmar que el episodio refleja el [episodio en inglés](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (por ejemplo, sin grandes inserciones o eliminaciones)

**English**
1. Before beginning, consult the [**conventions for translation**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
1. To signal that you are working on this, leave a comment.
- confirm that technical terms are not translated and are marked with bold
- review the translation and make improvements (for example, correct typographical errors, improve readability)
- fix broken links
- confirm that the episode mirrors the [English episode](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (e.g. no large insertions or deletions)

**Comment by spereyra** [comment]
Hecho en #72 
Se hicieron correcciones de tipeo, algo de traducción que faltaba y cambios menores para mejorar la legibilidad. Se cambio el uso de "renglon" a "fila" en todos los casos.

**Comment by raynamharris** [comment]
Gracias @spereyra. Muy buenos cambios.
