### ISSUE TITLE
revise new issue template 

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#20]
I meant to submit a pull request and ask for review from @orchid00 and @iglpdc, but I accidentally committed directly here 9ea8ee7c52c190b2d9c6fc89c40761e1eb7d2a3f. 

Can you take a look at the [issue template](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/.github/ISSUE_TEMPLATE.md) and let me know if this looks good. I would like for the default text to be in Spanish rather than English. So, I translated what Erin wrote and reworded it a little bit.

**Comment by orchid00** [comment]
Hi rayna, i've checked it and added little fixs
