### ISSUE TITLE
Revisar episodio 12: Divide-aplica-Combina

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#28]
Rmd archivo: [12-plyr.Rmd](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/_episodes_rmd/12-plyr.Rmd)

**Español**
- Antes de comenzar, consulte el [**Lineamientos de traducción**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
- Para indicar que estás trabajando en esto, deja un comentario.
- [x] confirmar que términos técnicos no son traducido y son marcado con negrita
- [x] revise la traducción y realice mejoras (por ejemplo, corregir errores tipográficos, mejorar la legibilidad)
- [x] arreglar enlaces rotos
- [x] confirmar que el episodio refleja el [episodio en inglés](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (por ejemplo, sin grandes inserciones o eliminaciones)

**English**
- Before beginning, consult the [**conventions for translation**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
- To signal that you are working on this, leave a comment.
- confirm that technical terms are not translated and are marked with bold
- review the translation and make improvements (for example, correct typographical errors, improve readability)
- fix broken links
- confirm that the episode mirrors the [English episode](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (e.g. no large insertions or deletions)

**Comment by xmnlab** [comment]
voy a revisarlo :)

**Comment by raynamharris** [comment]
hola @xmnlab. Puedes revisarlo esa semana? Gracias?

**Comment by xmnlab** [comment]
Si claro! voy a hacerlo mañana por la tarde :)

**Comment by xmnlab** [comment]
perdón por el atraso .. lo revisaré hoy ... gracias

**Comment by xmnlab** [comment]
una consulta .. hago los cambios o apenas apunto los cambios que me parecen necesarios?

**Comment by raynamharris** [comment]
puedes apuntar los cambios que me parecen necesarios
