### ISSUE TITLE
revisar episodio 13: Manipulación de Dataframes con dplyr

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#29]
Rmd archivo: [13-dplyr.Rmd](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/_episodes_rmd/13-dplyr.Rmd)

**Español**
- Antes de comenzar, consulte el [**Lineamientos de traducción**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
- Para indicar que estás trabajando en esto, deja un comentario.
- [x] eliminar la sintaxis de Markdown para palabras en negrita en título
- [x] confirmar que términos técnicos no son traducido y son marcado con negrita
- [x] revise la traducción y realice mejoras (por ejemplo, corregir errores tipográficos, mejorar la legibilidad)
- [x] arreglar enlaces rotos
- [x] confirmar que el episodio refleja el [episodio en inglés](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (por ejemplo, sin grandes inserciones o eliminaciones)
- [x] convertir todas las instancias de "dataframe" a "data frame"

**English**
- Before beginning, consult the [**conventions for translation**](https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md)
- To signal that you are working on this, leave a comment.
- remove markdown syntax for bolding in the title
- confirm that technical terms are not translated and are marked with bold
- review the translation and make improvements (for example, correct typographical errors, improve readability)
- fix broken links
- confirm that the episode mirrors the [English episode](https://github.com/swcarpentry/r-novice-gapminder/tree/gh-pages/_episodes_rmd) (e.g. no large insertions or deletions)
- convert all instances of "dataframe" to "data frame"

**Comment by Helysalgado** [comment]
revisandolo

**Comment by Helysalgado** [comment]
@raynamharris 
En los lineamientos dice :
          el dataframe     no data  frame.    y debe ir en negritas.

Y el punto 6 de cosas a revisar dice:
    convertir todas las instancias de "dataframe" a "data frame"

entonces, cual es el correcto?

**Comment by raynamharris** [comment]
hmm.  

En ingles, es "data frame" https://www.rdocumentation.org/packages/base/versions/3.4.3/topics/data.frame

y si, debe ir en negritas

**Comment by Helysalgado** [comment]
@raynamharris terminé la revisión. Revisados los puntos indicados arriba.

**Comment by raynamharris** [comment]
Gracias!!

**Comment by kevinalquicira** [comment]
@raynamharris  hola, terminé la revisión. Solo realicé un cambio de redacción en una frase, en general muy bien.
Saludos!
