### ISSUE TITLE
traducir la referencia

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#33]
El [reference.md](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/reference.md) solo se traduce parcialmente. Las secciones seguientes necesitan traducción. 

- [x] Funciones
- [x] Escribiendo datos
- [x] Split-apply-combine
- [x] Manejo de dataframe con dplyr
- [x] Manejo de dataframe con tidyr
- [x] Generando reportes con knitr
- [x] Buenas prácticas para escribir un buen código
- [x] Glosario

**Cómo contribuir:** 
1. Para mayor coherencia, busque el texto apropiado en el episodio en lugar de traducir directamente el [reference.md](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/reference.md)  
2. Agregue un comentario a continuación para indicar en qué sección está trabajando.
3. Marque la casilla cuando haya terminado

---
(In English)
**Rationale:** The [reference.md](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/reference.md) is only partially translated. The above sections need translation. 
**How to contribute:** 
1. For consistency, look for the appropriate text in the episode instead of directly translating this page.
1. Add a comment below to indicate which section you are working on. 
1. Check the box when you are finished.

**Comment by Helysalgado** [comment]
trabajando en este episodio

**Comment by Helysalgado** [comment]
@raynamharris The file to translate is the .md?

**Comment by raynamharris** [comment]
@Helysalgado Yes. The file to translate is the .md in this case. There is no assoicated .Rmd file.

**Comment by Helysalgado** [comment]
@raynamharris I finished the translation, but I can´t see the changes in the repository. I send  you an email.

**Comment by raynamharris** [comment]
Thanks! They were incorporated successfully here: https://github.com/swcarpentry/r-novice-gapminder-es/commit/b4235e206aa9536dd09713b83953247683534be4
