### ISSUE TITLE
Traducir la guía del instructor

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#35]
La guía del instructor en [guide.md](https://swcarpentry.github.io/r-novice-gapminder-es/guide/) necesita ser traducido.

Para indicar que estás trabajando en esto, deja un comentario 👇.

**Comment by spereyra** [comment]
Me pongo a trabajar en esto

**Comment by raynamharris** [comment]
Gracias @spereya!
