### ISSUE TITLE
Información sobre "Los Errores a la Parrilla"

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#39]
**Los Errores a la Parrilla** es un evento comunitario global para mejorar las lecciones de [Software Carpentry](http://swcarpentry.github.io/) y [Data Carpentry](http://www.datacarpentry.org/). Durante dos días, las comunidades se reúne en línea para aplastar y asar tantos errores como sea posible para preparar las lecciones de los lanzamientos oficiales. Usaremos GitHub y Slack para organizarnos. Para detalles de todos los grupos participantes, visite este sitio web: https://carpentries.github.io/2018-04-bug-bbq/

También habrá un evento en persona específicamente para la lección R-novice-gapminder-es en Buenos Aires el jueves 12 de abril de 18:30 a 21:00 en el [valo hublab](https://valohublab.com/). Se puede llegar un poco tarde y también se puede participar online.

**Formas de participar:**
1. podés leer la lista de [**Issues**](https://github.com/swcarpentry/r-novice-gapminder-es/issues), seleccione una lección para trabajar y hacer [**pull requests**](https://github.com/swcarpentry/r-novice-gapminder-es/pulls) para cambiar errores.
1. podés revisar y comentar sobre abiertos [**pull requests**](https://github.com/swcarpentry/r-novice-gapminder-es/pulls)
1. podés abrir un nuevo [**Issues**](https://github.com/swcarpentry/r-novice-gapminder-es/issues) o [**pull requests**](https://github.com/swcarpentry/r-novice-gapminder-es/pulls) si ve espacio para la mejora 

Hablamos más en este **issue** o por slack en [![Slack Status](https://img.shields.io/badge/Slack_Channel-swc--r--gapminder--es-E01563.svg)](https://swcarpentry.slack.com/messages/C9X9DN84V)

**Comment by raynamharris** [comment]
![alaplancha](https://user-images.githubusercontent.com/7544197/38506410-1f72989c-3bf0-11e8-9b48-55de159464d7.png)

**Comment by orchid00** [comment]
Super Rayna! despues del 12 creo que ya estara todo revisado :D bravo!!!

**Comment by raynamharris** [comment]
Thanks to everyone who participated! !Gracias a todos los que participaron!
