### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/r-novice-gapminder-es#44]
Hi @raynamharris @fmichonneau 

I'm slightly confused about two folders
_episodes_rmd_en and _episodes_rmd

In which of those folders should we review the translations for this lesson?

**Comment by fmichonneau** [comment]
`_episodes_rmd` is the Spanish one. `_episodes_rmd_en` is the English archival copy. It can probably be deleted now.

**Comment by raynamharris** [comment]
Agree. I say we delete the `_episodes_rmd_en` filess

**Comment by orchid00** [comment]
Should we do reviews in the _episodes_rmd ? 
cool, that's all I needed :D

**Comment by raynamharris** [comment]
Yes, all PRs should be made in the _episodes_rmd file. A maintainer uses `make serve` on a local computer to render all the .md files. See PR #46 for a link to how this works and to view the last build.

**Comment by fmichonneau** [comment]
You want to use `make site` to generate the files for the website. `make serve` does the same thing as `make site` but also starts a web server that allows you to preview the site dynamically in your browser.

**Comment by raynamharris** [comment]
Thanks for the clarification. I really liked being able to preview the site first in a browser.
