### ISSUE TITLE
"Finish " programa

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/r-novice-gapminder-es#53]
en la pagina principal el ultimo item del programa dice "Finish" despues del episodio 16 https://swcarpentry.github.io/r-novice-gapminder-es/
No se donde cambiarlo, pero deberia decir Final

**Comment by raynamharris** [comment]
para cambiar lo, se puede hacer un pull request en el styles-es repo aca
https://github.com/swcarpentry/styles-es/blob/gh-pages/_includes/syllabus.html

**Comment by raynamharris** [comment]
Closed with PR https://github.com/swcarpentry/styles-es/pull/9 to style to the style-es repo

**Comment by raynamharris** [comment]
Thanks @orchid00

**Comment by orchid00** [comment]
maybe something else is missing? the "Finish"  is still there

**Comment by fmichonneau** [comment]
pull requests in styles-es merged, and brought in in this repository. I'll do the same on the shell, and the git lessons

**Comment by orchid00** [comment]
yay!
