### ISSUE TITLE
Citacion

### ISSUE THREAD

**Issue by orchid00** [swcarpentry/r-novice-gapminder-es#54]
traducir https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/CITATION

con el nuevo zenodo id and corresponding new maintainers

Tambien escribir CITA en vez de CITE https://swcarpentry.github.io/r-novice-gapminder-es/ en el pie de pagina

**Comment by raynamharris** [comment]
Thanks @orchid00. 

- [ ] To translate CITE to CITA, you can create a pull request in the [styles-es/_includes/lesson_footer.html](https://github.com/swcarpentry/styles-es/blob/84943b90a013d5afe1708b16dad9c3df1fbe18e8/_includes/lesson_footer.html)
- [ ] To update the actual citation, we will need to wait for @fmichonneau to submit the lesson to Zenodo.

**Comment by fmichonneau** [comment]
Yes, it's correct the DOI and versions will need to be updated once the lesson is officially ready to be released, but in the meantime, you can translate the rest. Don't change the file name though as it's a community standard.

**Comment by raynamharris** [comment]
Thanks @orchid00. 
@fmichonneau we can update this later
