### ISSUE TITLE
La traduccion del episodio 7 no esta actualizada

### ISSUE THREAD

**Issue by monialo2000** [swcarpentry/r-novice-gapminder-es#57]
Hay una gran diferencia entre version en ingles y en español. El ingles es más simple, pero tiene documentación vieja (existe una distribución poisson en español, que se omitió en ingles, pero quedo comentario)

**Comment by raynamharris** [comment]
Mira @flor14 @monialo2000 ! 
Encontré el compromiso con el cambio. Sucedió en octubre, después de que comenzamos la traducción.

https://github.com/swcarpentry/r-novice-gapminder/commit/f60708b030f3c4479536476c3647080adfee129c#diff-f45d15c8b11189cc34e97c286736c366

**Comment by monialo2000** [comment]
Siii... exactamente lo que vimos!!!

**Comment by iglpdc** [comment]
Hola, @monialo2000!

Creo que es mejor la version en ingles, sin usar la distribucion de Poisson. A fin de cuentas, lo unico que queremos es demostrar que el `if` permite ejecutar partes de codigo dependiendo de una condicion.

Si quitamos la distrbucion de Poisson, deberiamos pensar si se podria mejorar el parrafo donde se introduce el bloque `else if`.

Que os parece este plan:

- [ ] abrir un issue en la version en ingles, para que se borre el comentario que hace referencia a la distribucion de Poisson.
- [ ] cambiar la version en espanhol para quitar la referencia a la distribucion de Poisson y hacerla similar al ingles.
- [ ] mejorar el parrafo que introduce el `else if` o no.

**Comment by monialo2000** [comment]
Si... me parece mejor sin Poisson. Hago el cambio que propones!
Gracias!!!

Monica

**Comment by flor14** [comment]
Que bueno que se haya encontrado el problema! Con @monialo2000 nos habiamos quedado con la duda!

**Comment by raynamharris** [comment]
Hola @monialo2000 y @flor14, me avisan si necessitas ayuda o si tienen preguntas con el PR

**Comment by flor14** [comment]
Hola Rayna! En cuanto podamos volvemos con esto! Espero que hayas llegado
bien a tu casa

**Comment by raynamharris** [comment]
@flor14 podes trabajar en eso esa semana? Si no, me avisa. Gracias!

**Comment by monialo2000** [comment]
Hola Rayna! Disculpa que no pude continuar con ese gap. Esta semana tengo
que realizarme una cirugia,  estas semanas fueron muy agitadas  y no puedo
ocuparme. Flor no se si vos podras, se que tambien estas complicada.
Yo calculo que por lo menos por 15 dias no voy a poder continuar.
Nuevamente me disculpo pero fue un tema inesperado de salud.

Les mando un beso grande,

Monica

**Comment by flor14** [comment]
Yes, I can! I will do it this week

Thank you
Florencia

**Comment by monialo2000** [comment]
Hola, Rayna! Espero estes muy bien!
Con @flor14 queriamos retomar las traducciones al español que habíamos
comenzado cuando estuviste por Buenos Aires. Yo por suerte, ya solucioné mi
tema de salud, así que nuevamente activa!
Si te parece, por favor avisanos cómo podríamos hacer.

Saludos,

Mónica

2018-04-19 13:52 GMT-03:00 Rayna M Harris <notifications@github.com>:

**Comment by raynamharris** [comment]
Hola Mónica! ¡Me alegra que estás bien! 

Creo que el comentario del 13 de abril describe el problema bastante bien y proporciona un camino a seguir. ¿Tiene sentido?

**Comment by monialo2000** [comment]
Hola Rayna! Como estas?
Ya estamos arreglando con Florencia para continuar la traducción la semana
que viene! Cualquier duda te consultamos!

Gracias!
Monica

**Comment by monialo2000** [comment]
Hi Rayna!
I don't understand the message: #57 is closed, that's ok!  but, I have to
make changes to #91 or is all ok?

Thanks,

Monica

El 6 jul. 2018 13:30, "Rayna M Harris" <notifications@github.com> escribió:

Closed #57 <https://github.com/swcarpentry/r-novice-gapminder-es/issues/57>
via #91 <https://github.com/swcarpentry/r-novice-gapminder-es/pull/91>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/swcarpentry/r-novice-gapminder-es/issues/57#event-1720649670>,
or mute the thread
