### ISSUE TITLE
Uso de la narración en primera persona en las episodos 2, 14 y 15

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#58]
La narración en primera persona de los episodios 2, 14 y 15 debe eliminarse. Ver PR https://github.com/swcarpentry/r-novice-gapminder/pull/367 y Issue https://github.com/swcarpentry/r-novice-gapminder/issues/302 para referencia.

**Comment by spereyra** [comment]
Cambie la narracion en primera persona en los episodios 2 y 15. En el 14 no encontre menciones en primera persona y no fue necesario. #60 y #61

**Comment by raynamharris** [comment]
Gracias @spereyra!
