### ISSUE TITLE
inconsistent code translations

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#78]
Occasionally, some code blocks are translated but many others are not. We should be consistent.

**Comment by Helysalgado** [comment]
Hola @raynamharris 
I found the Convenciones, and in the section "No se traduce" says 
https://github.com/Carpentries-ES/board/blob/master/Convenciones_Traduccion.md
"Nombres de variables en ejemplos y en general el código encerrado entre ~~~ ~~~ {: .bash}, {: .r}. Nota: Los comentarios dentro del código pueden traducirse si ven que al traducirlos las instrucciones serían más claras"

But, it has been suggested to translate some values ​​in the dataframes to make it more understandable. What do you suggest?

**Comment by nselem** [comment]
I have changed tortoiseshell for carey; this one was tough for me to understand in English (it is not a common word I think). I also replaced feline-data.csv for gatos-data.csv. The other variable names I consider are quite understandable as they are. As a maintainer, I will close the issue, but please feel free to re-open it if you feel that more work in this direction is needed.
