### ISSUE TITLE
Traducir "navbar.html"

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#8]
**Español**
- [ ]  el [**navbar**](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/_includes/navbar.html) necesitan traducción.
- Para indicar que estás trabajando en esto, deja un comentario.

**English**
- the [navbar](https://github.com/swcarpentry/r-novice-gapminder-es/blob/gh-pages/_includes/navbar.html) needs to be translated
- See [git-novice-es/_includes/navbar.html](https://github.com/swcarpentry/git-novice-es/blob/2a6de34fd54ded7ce43846e73c7664c69676afb8/_includes/navbar.html) for guidance
- To signal that you are working on this, leave a comment.

**Comment by fmichonneau** [comment]
Shouldn't this be translated in the styles-es repository directly? So all the Spanish lessons have the same translations for it?

**Comment by raynamharris** [comment]
That's what I thought. But it appears to be translated in the styles repo...
https://github.com/swcarpentry/styles-es/blob/gh-pages/_includes/navbar.html

**Comment by fmichonneau** [comment]
it might be out of sync. Let me bring in the latest version in this repo

**Comment by raynamharris** [comment]
Fixed with https://github.com/swcarpentry/r-novice-gapminder-es/pull/11
