### ISSUE TITLE
add Spanish translations of cheatsheets

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#82]
Some Spanish translations of R packages are available! Thanks @flor14 for pointing me to these!  https://www.rstudio.com/resources/cheatsheets/

We should add these to the lessons where appropriate! 
- [x] [ggplot](https://www.rstudio.com/wp-content/uploads/2015/04/ggplot2-spanish.pdf)

**Comment by avgarsow** [comment]
Another few lessons where these cheat sheets could be appropriate would be the: 

- [ ] Introducción a R y RStudio (Introducción a R cheat sheet) 
- [ ] Manipulación de data frames con dplyr (Data Wrangling and Data Transformation translated cheat sheet)
- [ ] Manipulación de data frames con tidyr (Data Wrangling and Data import translated cheat sheets)

**Comment by Helysalgado** [comment]
Se adicionó el link a la guía rapida de introducción a R, dentro del siguiente párrafo (última línea), en 01-rstudio-intro.Rmd

"Escribir un `?` antes del nombre de un comando abrirá la página de ayuda para ese comando. Además de proporcionar una 
descripción detallada del comando y cómo funciona, al desplazarse hacia la parte inferior de la página de ayuda generalmente 
se mostrarán ejemplos que ilustran el uso del comando. Veremos un ejemplo más adelante. 
Puedes consultar también ![las guías rápidas](https://raw.githubusercontent.com/rstudio/cheatsheets/master/translations/spanish/introduccion-a-r.pdf)
 disponibles en el sitio de de RStudio"

**Comment by Helysalgado** [comment]
Se vinculó la guía rapida en el sig párrafo:
"Afortunadamente, el paquete [`dplyr`](https://cran.r-project.org/package=dplyr) proporciona un conjunto de funciones 
(consulta la [guía rápida](https://raw.githubusercontent.com/rstudio/cheatsheets/master/translations/spanish/data-transformation_es.pdf) )  extremadamente útiles para manipular **data frames** y así reducir el número de repeticiones , la probabilidad de cometer errores y  el número de caracteres que hay que escribir. Como valor extra, puedes encontrar que la gramática de `dplyr` es más fácil de entender."

**Comment by Helysalgado** [comment]
Se puso la liga a la guía rápida de ggplot2 en el párrafo:

"Hoy aprenderemos acerca de **`ggplot2`**, que permite de manera sencilla crear gráficos 
complejos a partir de un conjunto de datos. Este paquete provee una estructura para que podamos especificar 
qué variables graficar, cómo deben ser presentadas y otras propiedades visuales generales 
([consulta la guía rápida de funciones](https://raw.githubusercontent.com/rstudio/cheatsheets/master/translations/spanish/data-visualization_es.pdf)). "

**Comment by nselem** [comment]
El link de la guía rapida del episodio 01-rstudio-intro.Rmd no estaba funcional, probablemente porque se trataba de cargarlo como imagen con "![]()" Le removí el "!" para dejarlo sólo como hiperrvínculo. Gracias por ponerlo, no sabía que existían en español.
