### ISSUE TITLE
Typo on Heading

### ISSUE THREAD

**Issue by rociotmartinez** [swcarpentry/r-novice-gapminder-es#92]
The heading 'Episodos' should be 'Episodios' - just a little typo!

**Comment by raynamharris** [comment]
:)

**Comment by raynamharris** [comment]
Thanks @rociotmartinez! Great catch! We can't fix that in this repo, but we can fix it over in the styles-es repo https://github.com/carpentries/styles-es/pull/13

**Comment by rociotmartinez** [comment]
OK! It is not important for the lesson itself, just an observation : ) Thanks for following this up @raynamharris !

**Comment by nselem** [comment]
Seems like fixed now! Please let me know if I am mistaken!
