### ISSUE TITLE
translate "cats" examples

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/r-novice-gapminder-es#93]
In the dataframe lessons, it would make more sense to translate coat, weight, likes_string, calico, black, tabby.

What are the best translations of these words?

- cats - gatos
- coat - capa? o color? 
- weight - peso
- likes_string - gusta_cuerda?
- calico - calico
- black - negro
- tabby - atigrado? o tabby?
- age - edad

**Comment by lauracion** [comment]
Hi Rayna,

My version of this:

* cats - gatos
* coat - color
* weight - peso
* likes_string - le_gusta_cuerda? I don´t know what "likes_string" is representing so it is difficult to do a meaningful translation. I this "likes_string" as in "the cat likes to play with a string" or as in "the cat likes to wear a leash"  or something else?
* calico - calicó
* black - negro
* tabby - atigrado
* age - edad

Hope it helps. :smile_cat:

**Comment by spereyra** [comment]
Agree with @lauracion's translations. 
I would suggest translating "likes_string" with "le_gusta_la_cuerda" as I believe the meaning here is "the cat likes to play with a string".

**Comment by lauracion** [comment]
In that case "le_gusta_la_cuerda" is a great translation.

**Comment by raynamharris** [comment]
awesome thanks @lauracion and @spereyra
