### ISSUE TITLE
typos en "Explorando data frames"

### ISSUE THREAD

**Issue by lauracion** [swcarpentry/r-novice-gapminder-es#95]
Some typos  in [Explorando dataframes](https://swcarpentry.github.io/r-novice-gapminder-es/05-data-structures-part2/index.html):

* It reads "Poder anexar dos data frame.", but it should read "Poder anexar dos data frame**s**."
* It reads "- en la última lección, donde recorrimos las estructuras básicas de R.", but it should read "- en la última lección, recorrimos todos los tipos y estructuras de datos báscias de R."
* It reads "En ésta lección,", but it should read "En **e**sta lección,"
* It reads "Para que funcione, no debemos tener `nrow(cats)` = `length(age)`.", but it should read "Para que funcione, debemos tener `nrow(cats)` = `length(age)`."
* It reads "permite los valores que originalmente estaba allí", but it should read "permite los valores que originalmente estaba**n** allí".
* It reads "También podemos eliminar columnas en un marco de datos.", but it should read "También podemos eliminar columnas en un data frame."
* It reads "por número o nobre de índice", but it should read "por número o no**m**bre de índice".
* It reads "Observe la coma sin nada antes", but it should read "Observ**a** la coma sin nada antes".
* It reads "Añadiendo a un data frame", but it should read "Añadiendo filas o columnas a un data frame"
* It reads "gapminder, ¿Qué piensas", but it should read "gapminder, ¿**q**ué piensas"
* It reads "en un script entonces podemos volver y editar en el futuro.", but it should read "en un script al que podremos volver y editar en el futuro."
* In the section "Puntos Clave" all bullets should finish with a "." or should not. Currently half of them finish with a dot and the other half does not.

**Comment by spereyra** [comment]
Fixed! Thank you @lauracion for these suggestions!
